### PR TITLE
Test-logger extension

### PR DESCRIPTION
**Pull request by f3l1x98**
This adds some additional functionality to the `test-logger` as discussed https://github.com/jvalue/jayvee/issues/430#issuecomment-1695315374

### CODE REVIEW

**Review by georg-schwarz — CHANGES_REQUESTED** [review]
Can you pls check if we can implement it by subclassing `DefaultLogger` instead to avoid duplicate logic?

**Comment by f3l1x98** [comment]
> Can you pls check if we can implement it by subclassing `DefaultLogger` instead to avoid duplicate logic?

I intended to (that is why it is still in WIP, after all subclassing DefaultLogger will require some visibility changes in the logger)

**Comment by georg-schwarz** [comment]
Ah wait, that will cause the dependency cycle again, right? Maybe we can move the default logger somewhere else?

**Comment by f3l1x98** [comment]
> Ah wait, that will cause the dependency cycle again, right? Maybe we can move the default logger somewhere else?

Yes you are right.
I have moved the `default-logger.ts` into `execution/logging`.

**Review by georg-schwarz — COMMENTED** [review]
LGTM. 

I have another use-case in mind: a program using Jayvee might want to extract the logs (instead of reading the std out).

Could you move it from the test to the regular library.

Another suggestion: store all logs in a common string array of a wrapper that lets you filter the different log levels. This way the order of log messages is preserved between the different log levels.

**Comment by f3l1x98** [comment]
I could do that, but would do so in a separate PR given that this is another feature.

**Review by georg-schwarz — APPROVED** [review]

**Pull request merged**
